name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy_functions:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Install dependencies
        env:
          CI: true
        run: |
          cd functions/backup
          yarn install
      - name: Build
        run: |
          cd functions/backup
          yarn build
      - name: Deploy
        run: |
          cd functions/backup/bin
          zip -r function.zip ./*
          aws lambda update-function-code --function-name=chess-backup --zip-file=fileb://function.zip
